name: "Voltronic"
description: "Monitor and control Voltronic based inverters from Home Assistant."
version: "1.0.0"
slug: "voltronic"
init: false
udev: true
devices:
  - /dev/ttyS0
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/hidraw0
  - /dev/hidraw1
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  mqtt_broker_host: "homeassistant"
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
  device_type: usb0

schema:
  mqtt_broker_host: str
  mqtt_username: str
  mqtt_password: str
  device_type: list(serial|usb-serial0|usb-serial1|usb0|usb1)
